// <auto-generated />
namespace Basketball.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class lmfao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lmfao));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110106408_lmfao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
